//! init — 為 OpenCode/其他 AI 生成專案概述檔

use std::fs;
use std::path::PathBuf;

use crate::commands::new_project::evolution_root;

/// 生成專案概述檔（讓 OpenCode 理解專案結構）
pub fn init(project_name: Option<&str>) {
    let root = evolution_root();

    match project_name {
        Some(name) => {
            let proj_path = root.join("projects").join(name);
            if !proj_path.exists() {
                eprintln!("✗ 專案 '{}' 不存在", name);
                eprintln!("  先建立：evolution new {}", name);
                std::process::exit(1);
            }
            generate_overview(&proj_path, name);
        }
        None => {
            // 對整個 Evolution 系統生成概述
            generate_system_overview(&root);
        }
    }
}

fn generate_overview(project_path: &PathBuf, name: &str) {
    println!("📋 生成專案概述：{}", name);

    // 讀取 evolution.yaml
    let config_path = project_path.join("evolution.yaml");
    let config_content = std::fs::read_to_string(&config_path)
        .unwrap_or_else(|_| "# 無設定檔".to_string());

    // 讀取 manifest.ev
    let manifest_path = project_path.join("manifest.ev");
    let manifest_content = std::fs::read_to_string(&manifest_path)
        .unwrap_or_else(|_| "# 無藍圖".to_string());

    // 列出 nodes/
    let nodes_path = project_path.join("nodes");
    let nodes = list_dir_entries(&nodes_path);

    // 列出 output/
    let output_path = project_path.join("output");
    let output = list_dir_entries(&output_path);

    let overview = format!(
        r#"# Evolution OS 專案概述 — {}

## 基本資訊
- 名稱：{}
- 設定：evolution.yaml
- 藍圖：manifest.ev

## 設定內容
{}

## 藍圖內容
{}

## Nodes（任務節點）
{}

## Output（輸出）
{}

---
Generated by Evolution OS init command
"#,
        name,
        name,
        config_content,
        manifest_content,
        nodes,
        output
    );

    let output_file = project_path.join("PROJECT.md");
    fs::write(&output_file, &overview).unwrap_or_else(|e| {
        eprintln!("✗ 無法寫入概述檔：{}", e);
        std::process::exit(1);
    });

    println!("  ✅ 概述檔已生成：{}", output_file.display());
    println!();
    println!("  下一步：");
    println!("    • 用 VS Code 開啟：code {}", output_file.display());
    println!("    • 給 OpenCode 看這個檔案讓他理解專案");
    println!("    • 然後用 evolution analyze \"任務\" 開始工作");
}

fn generate_system_overview(root: &PathBuf) {
    println!("📋 生成 Evolution OS 系統概述");

    // 列出所有專案
    let projects_path = root.join("projects");
    let projects = if projects_path.exists() {
        std::fs::read_dir(&projects_path)
            .map(|d| {
                d.filter_map(|e| e.ok())
                    .filter(|e| e.path().is_dir())
                    .map(|e| e.path().file_name().unwrap_or_default().to_string_lossy().to_string())
                    .collect::<Vec<_>>()
            })
            .unwrap_or_default()
    } else {
        vec![]
    };

    // 讀取 SPEC.md（如果存在的話）
    let spec_content = std::fs::read_to_string("SPEC.md")
        .unwrap_or_else(|_| "# 無 SPEC.md".to_string());

    // 讀取 VERSION_CONTROL.md
    let vc_content = std::fs::read_to_string("VERSION_CONTROL.md")
        .unwrap_or_else(|_| "# 無 VERSION_CONTROL.md".to_string());

    let overview = format!(
        r#"# Evolution OS 系統概述

## 專案列表
{}

## 系統架構
- **Layer 0**：Intent — 解析自然語言輸入
- **Layer 1**：Categorization — 分析複雜度（branches/diversity/complexity）
- **Layer 2**：Routing — 根據複雜度決定 Solo 或 Fork
- **Layer 3**：Execution — 執行 PlannerManifest

## 核心模組（src/）
- kernel/ — OS 核心（Process, Mailbox, Scheduler, ProcessTable, SysCall, SystemProcess）
- planner/ — 任務規劃（stages.rs, decision.rs, manifest.rs）
- runtime/ — 依賴圖執行引擎（GraphExecutor）
- node/ — 節點抽象（SkillNode, DynSkillNode, MemoryGraph, Registry）
- model/ — AI 後端派遣（OllamaBackend）
- skill/ — 技能實現（filesystem.rs 等）
- compiler/ — 多平台編譯器前端
- commands/ — CLI 子命令

## SPEC.md 內容摘要
{}

## 版本控制策略（VERSION_CONTROL.md）
{}

## CLI 指令
- `evolution new <name>` — 建立專案
- `evolution analyze <task>` — 分析並執行任務
- `evolution status` — 系統狀態
- `evolution init` — 生成系統概述
- `evolution init <project>` — 生成專案概述
- `evolution list-skills` — 列出可用技能
- `evolution shell` — 互動模式

## 預設模型
- llama3:latest（通用）
- mistral:7b-instruct（推理）
- gemma4:e4b（本地高效益）

---
Generated by Evolution OS init command
"#,
        if projects.is_empty() {
            "（無專案）".to_string()
        } else {
            projects.iter().map(|p| format!("- {}", p)).collect::<Vec<_>>().join("\n")
        },
        spec_content.lines().take(50).collect::<Vec<_>>().join("\n"),
        vc_content
    );

    let output_file = root.join("SYSTEM.md");
    fs::write(&output_file, &overview).unwrap_or_else(|e| {
        eprintln!("✗ 無法寫入概述檔：{}", e);
        std::process::exit(1);
    });

    println!("  ✅ 系統概述已生成：{}", output_file.display());
    println!();
    println!("  下一步：");
    println!("    • 給 OpenCode 看 SYSTEM.md 讓他理解整個系統");
    println!("    • 或用 evolution init <project> 生成特定專案概述");
}

fn list_dir_entries(path: &PathBuf) -> String {
    if !path.exists() {
        return "（目錄不存在）".to_string();
    }

    std::fs::read_dir(path)
        .map(|d| {
            d.filter_map(|e| e.ok())
                .map(|e| {
                    let name = e.file_name().to_string_lossy().to_string();
                    if e.path().is_dir() {
                        format!("  📁 {}", name)
                    } else {
                        format!("  📄 {}", name)
                    }
                })
                .collect::<Vec<_>>()
                .join("\n")
        })
        .unwrap_or_else(|_| "（無法讀取）".to_string())
}